function preload()
{
    walkSheet = loadImage('Assets/playerWalk.png')
    attackSheet = loadImage('Assets/playerAttack.png')
    enemyWalk = loadImage('Assets/enemyUnarmed.png')
    bricks = loadImage('Assets/bricks.jpg')
    darkStoneWall = loadImage('Assets/darkStoneWall.jpg')
    dead1 = loadImage('Assets/dead1.png')
    dead2 = loadImage('Assets/dead2.png')
    dead3 = loadImage('Assets/dead3.png')
    dead4 = loadImage('Assets/dead4.png')
    enemyAttack = loadImage('Assets/enemyAttack.png')
    enemyUnarmed = loadImage('Assets/enemyUnarmed.png')
    enemyArmed = loadImage('Assets/enemyArmed.png')
    grass = loadImage('Assets/grass.jpg')
    playerAttack = loadImage('Assets/playerAttack.png')
    playerWalk = loadImage('Assets/playerWalk.png')
    splatter1 = loadImage('Assets/splatter1.png')
    splatter2 = loadImage('Assets/splatter2.png')
    walls = loadImage('Assets/walls.png')
    wood = loadImage('Assets/wood.jpg')
    med = loadImage('Assets/med.png')
    gunShot = loadSound('Assets/GunShot.mp3')
    swordSwoosh = loadSound('Assets/SwordSwoosh.mp3')
    grunt = loadSound('Assets/Grunt.mp3')
}